"""Updated Friend model and seeds

Revision ID: c854225ceedd
Revises: 0b71a2e501c9
Create Date: 2023-08-01 20:13:47.429079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c854225ceedd'
down_revision = '0b71a2e501c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_birthdays_friend_id_friends'), 'friends', ['friend_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthdays', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_birthdays_friend_id_friends'), type_='foreignkey')
        batch_op.drop_column('friend_id')

    # ### end Alembic commands ###
